/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CCM
 */
public class ManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccJPanel
     */
    private JPanel userProcessContainer;
    private CarDirectory carDirectory;
    private Car car;
    
    
    ManageJPanel(JPanel userProcessContainer, CarDirectory carDirectory) {
        initComponents();
        this.carDirectory = carDirectory;
        this.userProcessContainer = userProcessContainer;
        populate(carDirectory,"bb");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        txtBrand = new javax.swing.JTextField();
        btnBrand = new javax.swing.JButton();
        btnMakeYear = new javax.swing.JButton();
        btnSerialNum = new javax.swing.JButton();
        btnModel = new javax.swing.JButton();
        btnAvailableCity = new javax.swing.JButton();
        btnAvailability = new javax.swing.JButton();
        btnMaintenance = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMakeYear = new javax.swing.JTextField();
        txtSerialNum = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtAvailableCity = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        txtMaintenance = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        btnMinMax = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnManList = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSearchFirst = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage ");

        tblCar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Make Year", "Min Seats", "Max Seats", "Serial Number", "Model", "Available City", "Availability", "Maintenance Cert"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCar);
        if (tblCar.getColumnModel().getColumnCount() > 0) {
            tblCar.getColumnModel().getColumn(0).setResizable(false);
            tblCar.getColumnModel().getColumn(1).setResizable(false);
            tblCar.getColumnModel().getColumn(2).setResizable(false);
            tblCar.getColumnModel().getColumn(3).setResizable(false);
            tblCar.getColumnModel().getColumn(4).setResizable(false);
            tblCar.getColumnModel().getColumn(5).setResizable(false);
            tblCar.getColumnModel().getColumn(6).setResizable(false);
            tblCar.getColumnModel().getColumn(7).setResizable(false);
            tblCar.getColumnModel().getColumn(8).setResizable(false);
        }

        btnBrand.setBackground(new java.awt.Color(204, 204, 204));
        btnBrand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBrand.setText("Brand");
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        btnMakeYear.setBackground(new java.awt.Color(204, 204, 204));
        btnMakeYear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMakeYear.setText("Make Year");
        btnMakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeYearActionPerformed(evt);
            }
        });

        btnSerialNum.setBackground(new java.awt.Color(204, 204, 204));
        btnSerialNum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSerialNum.setText("Serial number");
        btnSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumActionPerformed(evt);
            }
        });

        btnModel.setBackground(new java.awt.Color(204, 204, 204));
        btnModel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModel.setText("Model");
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });

        btnAvailableCity.setBackground(new java.awt.Color(204, 204, 204));
        btnAvailableCity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAvailableCity.setText("Available City");
        btnAvailableCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableCityActionPerformed(evt);
            }
        });

        btnAvailability.setBackground(new java.awt.Color(204, 204, 204));
        btnAvailability.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAvailability.setText("Availability");
        btnAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailabilityActionPerformed(evt);
            }
        });

        btnMaintenance.setBackground(new java.awt.Color(204, 204, 204));
        btnMaintenance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMaintenance.setText("Certified");
        btnMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Search Cars by Brand");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Search Cars by Make Year");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Search Cars by Model ");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(204, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });

        btnMinMax.setBackground(new java.awt.Color(204, 204, 204));
        btnMinMax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMinMax.setText("Seats");
        btnMinMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinMaxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Min Seats");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Max Seats");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Search Cars by Serial Number");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Search Cars bt Available City");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Search Available Cars");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Search Certified Cars");

        btnManList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnManList.setText("List");
        btnManList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManListActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Manufacturer List");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("First Available Car");

        btnSearchFirst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchFirst.setText("Search Car");
        btnSearchFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFirstActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtMin)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtMax)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                                .addGap(131, 131, 131)
                                                .addComponent(jLabel9))
                                            .addComponent(jLabel10)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(btnMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMakeYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSerialNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAvailableCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaintenance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaintenance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(208, 208, 208))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnView)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnDelete))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManList, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnSearchFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(532, 532, 532)
                .addComponent(btnRefresh)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnView))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMakeYear)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinMax))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSerialNum)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAvailableCity)
                                .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAvailability)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnMaintenance)
                    .addComponent(txtMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnSearchFirst))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(jLabel7)
                    .addComponent(btnManList))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        ArrayList<Car>search = carDirectory.searchBrand(txtBrand.getText(),carDirectory.getCarList());
        if (search.size()==0){
            JOptionPane.showMessageDialog(null, "Please search a valid Brand name","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            //ArrayList<Car> search = carDirectory.searchBrand(txtBrand.getText());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
        txtBrand.setText("");
    }//GEN-LAST:event_btnBrandActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCar.getSelectedRow();
        if(selectedRow >= 0){ 
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the car details","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_NO_OPTION){
                Car car = (Car) tblCar.getValueAt(selectedRow,0);
                carDirectory.deleteAccount(car);
                //populateTable();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please select a row from Table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnMakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeYearActionPerformed
        // TODO add your handling code here:
        /*if (carDirectory.searchMakeYear(txtMakeYear.getText())==null){
            JOptionPane.showMessageDialog(null, "Please search a valid Make Year","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            ArrayList<Car> search = carDirectory.searchMakeYear(txtMakeYear.getText());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }*/
        
        String serialNum = txtMakeYear.getText();
        try{
                Double.parseDouble(txtMakeYear.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter Number for Make Year");
            }
        txtSerialNum.setText("");
      if(serialNum == null || serialNum.equals("")){
          JOptionPane.showMessageDialog(null,"Make Year cant be empty");
          return;
          
      }
        else{
            ArrayList<Car> search = carDirectory.searchMakeYear(txtMakeYear.getText(),carDirectory.getCarList());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory );
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
      txtMakeYear.setText("");
    }//GEN-LAST:event_btnMakeYearActionPerformed

    private void btnSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumActionPerformed
        // TODO add your handling code here:
     
      try{
                Double.parseDouble(txtSerialNum.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter Number for Serial Number");
            }
      
      String serialNum = txtSerialNum.getText();
      if(serialNum == null || serialNum.equals("")){
          JOptionPane.showMessageDialog(null,"Serial Number cant be empty");
          return;
      }
        else{
            ArrayList<Car> search = carDirectory.searchSerialNum(txtSerialNum.getText(),carDirectory.getCarList());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
        txtSerialNum.setText("");
    }//GEN-LAST:event_btnSerialNumActionPerformed

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        // TODO add your handling code here:
        ArrayList<Car>search = carDirectory.searchModel(txtModel.getText(),carDirectory.getCarList());
        if (search.size()==0){
            JOptionPane.showMessageDialog(null, "Please search a valid Model name","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
          //ArrayList<Car> search = carDirectory.searchModel(txtModel.getText());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
        txtModel.setText("");
    }//GEN-LAST:event_btnModelActionPerformed

    private void btnAvailableCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableCityActionPerformed
        // TODO add your handling code here:
        ArrayList<Car>search= carDirectory.searchAvialableCity(txtAvailableCity.getText(),carDirectory.getCarList());
        if (search.size()==0)
        {
            JOptionPane.showMessageDialog(null, "Please search a valid City name","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
          //  ArrayList<Car> search = carDirectory.searchAvialableCity(txtAvailableCity.getText());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
        txtAvailableCity.setText("");
    }//GEN-LAST:event_btnAvailableCityActionPerformed

    private void btnAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailabilityActionPerformed
        // TODO add your handling code here:
        String searchh = txtAvailability.getText();
        if (searchh==null || searchh.equals("")){
            JOptionPane.showMessageDialog(null, "Please search a valid field value","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        else{
            ArrayList<Car> search = carDirectory.searchAvailabilty(txtAvailability.getText(),carDirectory.getCarList());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
        txtAvailability.setText("");
    }//GEN-LAST:event_btnAvailabilityActionPerformed

    private void btnMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceActionPerformed
        // TODO add your handling code here:
        String searchh = txtMaintenance.getText();
        if (searchh==null || searchh.equals("")){
            JOptionPane.showMessageDialog(null, "Please search a valid field value","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            ArrayList<Car> search = carDirectory.searchMaintenanceCert(txtMaintenance.getText(),carDirectory.getCarList());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
        }
        txtMaintenance.setText("");
    }//GEN-LAST:event_btnMaintenanceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void btnMinMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinMaxActionPerformed
        // TODO add your handling code here:
        
        int max = Integer.parseInt(txtMax.getText());
        int min = Integer.parseInt(txtMin.getText());
        ArrayList<Car> search = carDirectory.searchMinMax(min, max, carDirectory.getCarList());
        SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        txtMin.setText("");
        txtMax.setText("");
    }//GEN-LAST:event_btnMinMaxActionPerformed

    private void btnSearchFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFirstActionPerformed
        // TODO add your handling code here:
            
            ArrayList<Car> search = carDirectory.searchFirstCar(txtAvailability.getText(),carDirectory.getCarList());
            SearchJPanel panel = new SearchJPanel(userProcessContainer, search, carDirectory);
            userProcessContainer.add("SearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                             
       
        
        
        
    }//GEN-LAST:event_btnSearchFirstActionPerformed

    private void btnManListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManListActionPerformed
        // TODO add your handling code here:
       
           ManJPanel panel = new ManJPanel(userProcessContainer, carDirectory);
            userProcessContainer.add("ManJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer); 
           
                             
        
        
    }//GEN-LAST:event_btnManListActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCar.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row");
        
        }
        else{
            Car car = (Car) tblCar.getValueAt((selectedRow), 0);
            ViewJPanel panel = new ViewJPanel(userProcessContainer, car);
            userProcessContainer.add("ViewJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);  
        
           
        } 
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailability;
    private javax.swing.JButton btnAvailableCity;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMaintenance;
    private javax.swing.JButton btnMakeYear;
    private javax.swing.JButton btnManList;
    private javax.swing.JButton btnMinMax;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchFirst;
    private javax.swing.JButton btnSerialNum;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCar;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtMaintenance;
    private javax.swing.JTextField txtMakeYear;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables

    void populate(CarDirectory carList, String bb) {
         DefaultTableModel dtm = (DefaultTableModel) tblCar.getModel();
        dtm.setRowCount(0);
        for(Car car : carDirectory.getCarList()){
            if(car.getBrand().equals(bb)|| bb.equals("bb")){
            Object row[] = new Object[9];
            row[0] = car;
            row[1] = car.getMakeYear();
            row[2] = car.getMinSeats();
            row[3] = car.getMaxSeats();
            row[4] = car.getSerialNum();
            row[5] = car.getModel();
            row[6] = car.getAvialableCity(); 
            row[7] = car.isAvailabilty();
            row[8] = car.isMaintenanceCert();
            dtm.addRow(row);
        } //To change body of generated methods, choose Tools | Templates.
    }

    

    }
}